### ISSUE TITLE
代码大概什么时候发布？

### ISSUE THREAD

**Issue by nopeiyu** [Shimingyi/MotioNet#1]
论文很精彩，解决了很多之前的论文很少涉及的问题，如脚贴地的问题、绝对位移的问题、骨骼长度适配问题，很想实验一下，不知道代码什么时候发布啊

**Comment by Shimingyi** [comment]
你好，感谢对工作的肯定，代码会尽快发布。您可以关注本项目，有更新会及时推送。
Hello, thanks for the attention, the library will be released as soon as possible. You can star our repository to get the notification on time.
