### ISSUE TITLE
About multi-GPU operation

### ISSUE THREAD

**Issue by Z-Z-J** [Shimingyi/MotioNet#10]
I seem to find two code errors！
In    base_trainer.py    
code: 
if gpu_id > n_gpu:
            msg = "Warning: The number of GPU\'s configured to use is {}, but only {} are available on this machine.".format(n_gpu_use, n_gpu)
                            
                                problem :   n_gpu_use is not defined
code：
list_ids = list([gpu_id])
if len(device_ids) > 1:
            self.model = torch.nn.DataParallel(model, device_ids=device_ids)
            
                         problem:  len(device_ids)  is  always  1,so cant use multi-GPU

**Comment by Shimingyi** [comment]
Now I havn't implemented multi-GPU training because this model doesn't require a lot of resourecs. But I will support it to support multi-GPU training, thanks for your feekback!

**Comment by anas-zafar** [comment]
Hi @Shimingyi, were you have to implement multi-GPU training?
