### ISSUE TITLE
About valid !!

### ISSUE THREAD

**Issue by Z-Z-J** [Shimingyi/MotioNet#11]
![QQ截图20200913211051](https://user-images.githubusercontent.com/53818279/93018901-e5dda900-f605-11ea-940d-7de474d2da06.png)

First, a is defined ,but not use .
Second, alphas is a list , why only use alphas[0] ??

I look forward to your answer !!!!  Thank you !!!

**Comment by Shimingyi** [comment]
```a``` is just a temporary variant for debugging, I will delete it in next commit. 
 The operation is running on the batchwise, and when testing, the batchsize is 1. If you output the shape of ```alpha``` here, you will find the fist dimension value is 1. so we can use [0] to get it.
