### ISSUE TITLE
about: achieving temporal coherence naturally in paper

### ISSUE THREAD

**Issue by miss-rain** [Shimingyi/MotioNet#19]
Great project!

I read your paper, in the sixth part:CONCLUSION, LIMITATIONS, AND FUTURE WORK:

This is the original text:  
 Finally, since our system is trained in the space of motions, the inherent smoothness of human motions is learned from the data, **achieving temporal coherence naturally**.

My question:
 **achieving temporal coherence naturally**   .
Does it mean real-time? The input and output are real-time?

thanks!

**Comment by Shimingyi** [comment]
Answered by email. 
Short summary: Temporal coherence doesn't mean real-time performance, it's a metric on the output quality. If we want to extend this method to real-time, an offset would be applied which uses [0, 40] to predict [40, 50] rather than[0, 40] predicts [0, 40] currently.
