### ISSUE TITLE
wild_gt_tcc.pth error

### ISSUE THREAD

**Issue by guker** [Shimingyi/MotioNet#23]
```python
python evaluate.py -r ./checkpoints/wild_gt_tcc.pth -i demo
```
RuntimeError: ./checkpoints/wild_gt_tcc.pth is a zip archive (did you mean to use torch.jit.load()?)

**Comment by Shimingyi** [comment]
Hi @guker , what's your pytorch version? Storing checkpoint with zip is a new feature for pytorch>=1.6 so I will suggest to update it.

**Comment by guker** [comment]
> Hi @guker , what's your pytorch version? Storing checkpoint with zip is a new feature for pytorch>=1.6 so I will suggest to update it.

so i should update pytorch version >=1.6?

**Comment by Shimingyi** [comment]
> > Hi @guker , what's your pytorch version? Storing checkpoint with zip is a new feature for pytorch>=1.6 so I will suggest to update it.
> 
> so i should update pytorch version >=1.6?

Yes
