### ISSUE TITLE
code/tools for post processing

### ISSUE THREAD

**Issue by JinchengWang** [Shimingyi/MotioNet#26]
If it is convenient, could you release the code/tools for IK post processing demonstrated in your video? 
Thanks in advance!

**Comment by Shimingyi** [comment]
It's great, but actually I have no planning to release the IK code becuase it wasn't done by myself. But may I share you some useful code in our another project [Deep-motion-editing](https://github.com/DeepMotionEditing/deep-motion-editing/blob/ade1342ce76de92e61f3d1016c8d286294f2ea58/retargeting/models/IK.py), it might be helpful!

**Comment by JinchengWang** [comment]
Thanks! That helps :D
