### ISSUE TITLE
Question about Training Time

### ISSUE THREAD

**Issue by JinchengWang** [Shimingyi/MotioNet#27]
What is your best estimate of the amount of time it takes to train the network? And what kind of GPU did you use?

**Comment by Shimingyi** [comment]
Hi @JinchengWang , I haven't recorded the training time. But in genral, you can reach the performance about 55mm in one hours, and a complete training will take extra few hours. The model can be trained on all Nvidia GPUs which support Cuda and cudnn, you just need to install a suitable pytorch-gpu. I have experiences to train the model on gtx 1080, titan xp and rtx 3070 which can reach same performance on the accuracy.

**Comment by JinchengWang** [comment]
Thank you! That was fast oдo

**Comment by Shimingyi** [comment]
Because the network doesn't use image feature as input, so the tensor dimension is flexible. And also, we haven't predicted the camera parameters which requires lots of optimization steps in the training : ) Feel free if you have any idea on the extension if I can help.
