### ISSUE TITLE
Missing heatmap_utils in utils?

### ISSUE THREAD

**Issue by eric-cornellvel** [Shimingyi/MotioNet#3]
Thank you for making this amazing project available.

I have encountered the error when I tried to run the evaluate.py script either on h36m or wild video demo.

`File "evaluate.py", line 7, in <module>
    import model.model as models
  File "/content/MotioNet/model/model.py", line 9, in <module>
    from model import model_zoo
  File "/content/MotioNet/model/model_zoo.py", line 7, in <module>
    from utils import heatmap_utils
ImportError: cannot import name 'heatmap_utils' i

I check the utils folder and it seems it doesn't include the heatmap_utils file.

**Comment by Shimingyi** [comment]
Thanks for the feedback, I removed it already.
