### ISSUE TITLE
prepare CMU issue

### ISSUE THREAD

**Issue by aloizo03** [Shimingyi/MotioNet#32]
When i run the command python ./data/prepare_cmu.py to prepare the cmubvh dataset print me this error
Traceback (most recent call last):
  File "./data/prepare_cmu.py", line 11, in <module>
    bvh_files = util.make_dataset(['/mnt/dataset/cmubvh'], phase='bvh', data_split=1, sort_index=0)
  File "./utils/util.py", line 21, in make_dataset
    assert os.path.isdir(dataroot), '%s is not a valid directory' % dataroot
AssertionError: /mnt/dataset/cmubvh is not a valid directory

In the file data in repository i make the mnt/dataset/cmubvh and in the cmubvh i storage all the files that you tell in read me 
Best Antreas

**Comment by Shimingyi** [comment]
Hi Antreas, 

You should make a new folder in /mnt/dataset/cmubvh if you want to use the code without any updates. Now you make a folder in the repository path? Maybe it's better to update the path in line 11 with the new absolute path...

**Comment by aloizo03** [comment]
Hi Mingyi 
I updated beffore make the issue commit and i get the same message.

**Comment by Shimingyi** [comment]
Would you mind show me some screenshorts about your folder structure? For example, where do you store the bvh files, and how do you use it in the code.

**Comment by aloizo03** [comment]
In the prepareCMU i have the bvh_files = util.make_dataset(['/MotioNet-master/dataset/cmubvh'], phase='bvh', data_split=1, sort_index=0) like this and the bvh file are storage into 
![image](https://user-images.githubusercontent.com/55096983/106391036-fdba9b80-63f3-11eb-9e0d-a21f02799d77.png)

**Comment by Shimingyi** [comment]
Hi Andreas, I found two problems here. 
The path of this folder is not `/MotioNet-master/dataset/cmubvh`, it should be like `/home/[username]/Documents/EPL400/MotioNet-master/...`. And also, you should take out [these files](https://github.com/Shimingyi/MotioNet/blob/master/data/cmu_file_list) in this folder rather than put them in sub-folder.

**Comment by aloizo03** [comment]
Hi Mingyi
Thanks very much for the help now work all perfect with the cmu. I will close the issue now.
Best regards Andreas.
