### ISSUE TITLE
About the output of OpenPose 

### ISSUE THREAD

**Issue by Nisekoixmy** [Shimingyi/MotioNet#4]
HI guys,

Thanks for this great work. I tried your code and found it is good on hm3.6 testset. However, I'm wondering what is the output format of OpenPose, because I'm using Python API of OpenPose. And I know there is a 'datum.PoseKeypoints' of OpenPose as outputs. Could you please provide a guideline or a script about what the outputs of OpenPose should be?

Thank you very much.

Best regards,
Nisekoi.

**Comment by Nisekoixmy** [comment]
seems just need json directly from OpenPose? I will give it a try. Thank you.

**Comment by Shimingyi** [comment]
Right, just need the json file from OpenPose, without any other process:
```
./build/examples/openpose/openpose.bin --video [input_video] --write_json [output_folder] --display 0 --render_pose 0
```

**Comment by Nisekoixmy** [comment]
> Right, just need the json file from OpenPose, without any other process:
> 
> ```
> ./build/examples/openpose/openpose.bin --video [input_video] --write_json [output_folder] --display 0 --render_pose 0
> ```

Yeah, I tried it same as you provided. Thanks! 
Btw, it will be great if you provide a flag to control smoothing pre-processing for 2d outputs in evaluate.py.

Anyway, thank you again! I will close this issue.
