### ISSUE TITLE
Blender visualization issue.

### ISSUE THREAD

**Issue by lakpa-tamang9** [Shimingyi/MotioNet#43]
I tried to visualize the bvh files using blender. The resulting animation is upside down. Any solution? The initial T-pose is correct but after the second frame the video orientation becomes upside down. 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/54692758/158526080-ad2a940a-95fc-4f67-a8a9-4ffc91cfa35d.png">

**Comment by Shimingyi** [comment]
Hi @lakpa-tamang9 , for avoiding the camera view ambiguity(different poses on different cameras will yield the same 2d projection), the predicted human motion is always in camera space, which means you should rotate it manually. You can find more explanation in Martinez's paper [1], which provides a baseline to this kind of joint position-based prediction. 
<img width="340" alt="20220316142606" src="https://user-images.githubusercontent.com/7709951/158529520-f906a8fb-21cc-4313-83f5-3e54ab83493d.png">

1. Martinez, Julieta, et al. "A simple yet effective baseline for 3d human pose estimation." Proceedings of the IEEE international conference on computer vision. 2017.
