### ISSUE TITLE
BVH Output is upside down

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [Shimingyi/MotioNet#46]
@Shimingyi @kfiraberman  I'm getting output upside down while running this command,

`python evaluate.py -r ./checkpoints/wild_gt_tcc.pth -i demo`

![Screenshot (34)](https://user-images.githubusercontent.com/38744737/165322561-d7f41b6f-48d8-46dd-bab4-4b9495a6bb74.png)

please, help me with this issue.

**Comment by Shimingyi** [comment]
@Harsh-Vavaiya 
You can find some explanations here https://github.com/Shimingyi/MotioNet/issues/43 , I am working on these issues and will commit a new patch for that. (expected in 1st, May).
