### ISSUE TITLE
Where is wild_gt_cta.pth?

### ISSUE THREAD

**Issue by zhouhang95** [Shimingyi/MotioNet#7]
I only find wild_gt_tcc.pth in google driver.

**Comment by Shimingyi** [comment]
I change it to ```wild_gt_tcc.pth```.

**Comment by zhouhang95** [comment]
python evaluate.py -r ./checkpoints/wild_gt_tcc.pth -i data/example/0

Building the network
Traceback (most recent call last):
  File "evaluate.py", line 137, in <module>
    main(config, args, output_folder)
  File "evaluate.py", line 73, in main
    parameters = [torch.from_numpy(np.array(item)).float().to(device) for item in h36m_loader(config, is_training=True).dataset.get_parameters()]
  File "/home/student/zhouhang/MotioNet-master/data/data_loaders.py", line 11, in __init__
    self.dataset = h36m_dataset.h36m_dataset(config, is_train=is_training)
  File "/home/student/zhouhang/MotioNet-master/data/h36m_dataset.py", line 22, in __init__
    positions_set = np.load('./data/data_h36m.npz', allow_pickle=True)['positions_3d'].item()
  File "/home/student/zhouhang/anaconda3/envs/pth041py3/lib/python3.5/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/data_h36m.npz'

**Comment by Shimingyi** [comment]
You need to download these numpy files to _./data_ folder firstly: [Google Drive](https://drive.google.com/drive/folders/1mvRPqtsNp46grBQ9feYish8evhEkm_9O). Please refer to our [quick start](https://github.com/Shimingyi/MotioNet#quick-start).

**Comment by zhouhang95** [comment]
python evaluate.py -r ./checkpoints/wild_gt_tcc.pth -i data/example/0

Building the network
/home/student/zhouhang/MotioNet-master/utils/Animation.py:563: RuntimeWarning: invalid value encountered in true_divide
  rotations = rotations / np.repeat(np.expand_dims(np.sqrt(np.sum(np.square(rotations), axis=-1)), axis=-1), 4, axis=-1)
The bvh file of 0 has been saved!
