### ISSUE TITLE
How to open .bvh format files?

### ISSUE THREAD

**Issue by Z-Z-J** [Shimingyi/MotioNet#9]
Thank you very much for your work.
I want to know how to use .bvh file to generate animation,as demonstrated in your video.

**Comment by Shimingyi** [comment]
You can import the bvh file to [Blender](https://www.blender.org/) to the see same visualization like what we show. 
In addition,  if you want to drive a mesh model with this bvh data, it requires a little Animation acknowledge like skining and rigging.
